import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { DateTime } from 'luxon'

interface WaveRecord { timestamp: string; localDate: string; good: boolean; waveHs: number | null; waveTp: number | null; waveTa: number | null; waveDp: number | null }
interface SstRecord { timestamp: string; localDate: string; good: boolean; temperature: number | null }
interface DailyWaveSummary { date: string; year: number; month: number; day: number; observationCount: number; validWaveObservationCount: number; waveHeightMean: number | null; waveHeightP10: number | null; waveHeightP90: number | null; waterTempMean: number | null; dominantPeriodMean: number | null; averagePeriodMean: number | null; meanWaveDirection: number | null }

const splitCsv = (line: string) => line.match(/(?:"([^"]*(?:""[^"]*)*)"|([^,]*))(?:,|$)/g)?.map((cell) => cell.replace(/,$/, '').replace(/^"|"$/g, '').replace(/""/g, '"')) ?? []
const parseCsv = (text: string) => { const [header, , ...rows] = text.trim().split(/\r?\n/); const fields = splitCsv(header); return rows.map(splitCsv).map((row) => Object.fromEntries(fields.map((field, index) => [field, row[index] ?? '']))) }
const number = (value: string) => { const parsed = Number(value); return Number.isFinite(parsed) && parsed !== -999.99 ? parsed : null }
const localDate = (timestamp: string) => { const utc = DateTime.fromISO(timestamp, { zone: 'utc' }); return utc.isValid ? utc.setZone('America/Los_Angeles').toISODate() : null }
const valid = (values: Array<number | null>) => values.filter((value): value is number => value !== null && Number.isFinite(value))
const mean = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null
const percentile = (values: number[], p: number) => { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); const position = (sorted.length - 1) * p; const low = Math.floor(position), high = Math.ceil(position); return sorted[low] + (sorted[high] - sorted[low]) * (position - low) }
const circularMean = (values: number[]) => { if (!values.length) return null; const radians = values.map((value) => value * Math.PI / 180); return (Math.atan2(mean(radians.map(Math.sin))!, mean(radians.map(Math.cos))!) * 180 / Math.PI + 360) % 360 }
const groupByDate = <T extends { localDate: string }>(records: T[]) => records.reduce((groups, record) => { (groups.get(record.localDate) ?? groups.set(record.localDate, []).get(record.localDate)!).push(record); return groups }, new Map<string, T[]>())

function parseWave(text: string): WaveRecord[] { return parseCsv(text).flatMap((row) => { const date = localDate(row.time); if (!date) return []; return [{ timestamp: row.time, localDate: date, good: Number(row.waveFlagPrimary) === 1, waveHs: number(row.waveHs), waveTp: number(row.waveTp), waveTa: number(row.waveTa), waveDp: number(row.waveDp) }] }) }
function parseSst(text: string): SstRecord[] { return parseCsv(text).flatMap((row) => { const date = localDate(row.time); if (!date) return []; return [{ timestamp: row.time, localDate: date, good: Number(row.sstFlagPrimary) === 1, temperature: number(row.sstSeaSurfaceTemperature) }] }) }

function summary(date: DateTime, waves: WaveRecord[], sst: SstRecord[]): DailyWaveSummary {
  const goodWaves = waves.filter((record) => record.good); const waveValues = valid(goodWaves.map((record) => record.waveHs)); const goodSst = sst.filter((record) => record.good)
  return { date: date.toISODate()!, year: date.year, month: date.month, day: date.day, observationCount: waves.length, validWaveObservationCount: waveValues.length, waveHeightMean: mean(waveValues), waveHeightP10: percentile(waveValues, .1), waveHeightP90: percentile(waveValues, .9), waterTempMean: mean(valid(goodSst.map((record) => record.temperature))), dominantPeriodMean: mean(valid(goodWaves.map((record) => record.waveTp))), averagePeriodMean: mean(valid(goodWaves.map((record) => record.waveTa))), meanWaveDirection: circularMean(valid(goodWaves.map((record) => record.waveDp))) }
}

function report(days: DailyWaveSummary[], waves: WaveRecord[], sst: SstRecord[]) {
  const monthly = Array.from({ length: 12 }, (_, index) => { const records = days.filter((day) => day.month === index + 1); const counts = records.map((day) => day.validWaveObservationCount); const sstCounts = records.map((day) => day.date).map((date) => sst.filter((record) => record.good && record.localDate === date && record.temperature !== null).length); return { month: index + 1, calendarDays: records.length, validWaveDays: records.filter((day) => day.waveHeightMean !== null).length, insufficientWaveDays: records.filter((day) => day.waveHeightMean === null).length, validSstDays: records.filter((day) => day.waterTempMean !== null).length, missingSstDays: records.filter((day) => day.waterTempMean === null).length, medianWaveCount: percentile(counts.filter(Boolean), .5), minWaveCount: counts.length ? Math.min(...counts) : 0, maxWaveCount: counts.length ? Math.max(...counts) : 0, medianSstCount: percentile(sstCounts.filter(Boolean), .5) } }); const qa = { waveRecordsDownloaded: waves.length, goodWaveRecordsRetained: waves.filter((record) => record.good).length, sstRecordsDownloaded: sst.length, goodSstRecordsRetained: sst.filter((record) => record.good).length, validWaveDays: days.filter((day) => day.waveHeightMean !== null).length, missingWaveDays: days.filter((day) => day.waveHeightMean === null).length, validTemperatureDays: days.filter((day) => day.waterTempMean !== null).length, missingTemperatureDays: days.filter((day) => day.waterTempMean === null).length, monthly }; return qa
}

async function main() {
  const waves = parseWave(await readFile(resolve('data/raw/cdip-142-wave-2025.csv'), 'utf8')); const sst = parseSst(await readFile(resolve('data/raw/cdip-142-sst-2025.csv'), 'utf8')); const wavesByDate = groupByDate(waves), sstByDate = groupByDate(sst); const start = DateTime.fromISO('2025-01-01', { zone: 'America/Los_Angeles' }); const days = Array.from({ length: 365 }, (_, index) => { const date = start.plus({ days: index }); const key = date.toISODate()!; return summary(date, wavesByDate.get(key) ?? [], sstByDate.get(key) ?? []) })
  for (let month = 1; month <= 12; month++) { const records = days.filter((day) => day.month === month); const median = percentile(records.map((day) => day.validWaveObservationCount).filter(Boolean), .5) ?? 0; for (const day of records.filter((day) => day.validWaveObservationCount < median * .5)) { day.waveHeightMean = null; day.waveHeightP10 = null; day.waveHeightP90 = null } }
  for (const day of days) if (day.waveHeightMean !== null && !(day.waveHeightP10! <= day.waveHeightMean && day.waveHeightMean <= day.waveHeightP90!)) throw new Error(`Percentile validation failed for ${day.date}`)
  for (const record of waves.filter((record) => record.good)) { if (record.waveHs !== null && record.waveHs < 0) throw new Error('Negative waveHs'); if (record.waveTp !== null && (record.waveTp < 0 || record.waveTp > 40)) throw new Error('waveTp outside CDIP metadata bounds'); if (record.waveTa !== null && (record.waveTa < 0 || record.waveTa > 40)) throw new Error('waveTa outside CDIP metadata bounds'); if (record.waveDp !== null && (record.waveDp < 0 || record.waveDp > 360)) throw new Error('waveDp outside valid range') }
  if (days.some((day) => Object.values(day).some((value) => typeof value === 'number' && !Number.isFinite(value)))) throw new Error('Non-finite processed value')
  const output = { station: { id: '142', name: 'San Francisco Bar, CA', ndbcWmoId: '46237', source: 'Coastal Data Information Program (CDIP), Scripps Institution of Oceanography', timezone: 'America/Los_Angeles' }, year: 2025, units: { waveHeight: 'm', waterTemperature: 'C', wavePeriod: 's', waveDirection: 'degrees' }, days }
  await mkdir(resolve('public/data'), { recursive: true }); await writeFile(resolve('public/data/cdip-142-2025-daily.json'), JSON.stringify(output, null, 2)); const qa = report(days, waves, sst); await writeFile(resolve('data/cdip-142-2025-qa.json'), JSON.stringify(qa, null, 2)); console.log(JSON.stringify(qa, null, 2))
}
main().catch((error: unknown) => { console.error(error); process.exitCode = 1 })
